apiVersion: v1
entries:
  clusterpedia:
  - apiVersion: v2
    appVersion: v0.4.1
    created: "2022-08-17T14:17:49.111199+08:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.x.x
    - condition: mysql.enabled
      name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.x.x
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: A Helm chart for Kubernetes
    digest: 8edc17ac7f5f62c2b2f3a7c146555eb416783114ecb14afb46d7ee6a89579e34
    name: clusterpedia
    type: application
    urls:
    - https://github.com/clusterpedia-io/clusterpedia/releases/download/clusterpedia-0.4.1.tgz
    version: 0.0.2
generated: "2022-08-17T14:17:49.099224+08:00"
